version: "3.9"
networks:
  roboshop:
    driver: bridge
services:
  web:
    image: naveen2809/web:v1
    container_name: web
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - shipping
    - user
    - cart
    - mysql
  mongodb:
    image: naveen2809/mongodb:v1
    container_name: mongodb
  catalogue:
    image: naveen2809/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis
  user:
    image: naveen2809/user:v1
    container_name: user
    depends_on:
    - mongodb
    - redis
  cart:
    image: naveen2809/cart:v1
    container_name: cart
    depends_on:
      - redis
      - catalogue
  mysql:
    image: naveen2809/mysql:v1
    container_name: mysql
  shipping:
    image: naveen2809/shipping:v1
    container_name: shipping
    depends_on:
      - mysql
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
  payment:
    image: naveen2809/payment:v1
    container_name: payment
    depends_on:
    - rabbitmq
  ratings:
    image: naveen2809/ratings:v1
    container_name: ratings
    depends_on:
    - mysql